name: Server Workflow
on:
    push:
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Install NodeJs
              uses: actions/setup-node@v5
            - name: Print Node Version
              run: node -v
            - name: Print NPM Version
              run: npm -v
            - name: Navigate to Server Directory
              run: |
                  pwd
                  cd ./server
                  pwd
                  ls -la
            - name: Install Dependencies
              run: npm install
